name: Run playwright tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs at minute 0 of every hour
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Start Frontend & Backend
      run: |
        npm run dev &         # Frontend
        php artisan serve &   # Backend
        sleep 10              # Wait for servers
    
    - name: Run Playwright tests
      run: npx playwright test --workers=5
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
