# name: Run playwright tests
# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '0 * * * *'  # Runs at minute 0 of every hour
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]

# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v4
#       with:
#         node-version: '20.x'
    
#     - name: Install dependencies
#       run: npm ci
    
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps

#     - name: Install PHP & Composer
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '8.1' # Set the PHP version required by your project
#         tools: composer
    
#     - name: Install Laravel Dependencies
#       run: composer install --no-progress --no-suggest --prefer-dist

#     - name: Start Frontend & Backend
#       run: |
#         LARAVEL_BYPASS_ENV_CHECK=1 npm run dev &  # Start frontend
#         php artisan serve &                        # Start backend
#         sleep 10                                   # Wait for servers
    
#     - name: Run Playwright tests
#       run: npx playwright test --workers=5
    
#     - uses: actions/upload-artifact@v4
#       if: always()
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30
